<a href="https://colab.research.google.com/github/SoorajSundar1505/MachineLearning/blob/master/ML_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
print(9+67*2)

143


Print function


In [ ]:
from time import process_time


In [30]:
python_list = [i for i in range(10000)]
# for i in range(10000):
#   python_list.append(i)
# print(python_list)

start_time = process_time()
python_update_list = [i+5 for i in python_list]
end_time = process_time()
# print(python_update_list)
print(end_time-start_time)

0.001202091999999766


In [ ]:
import numpy as np



In [ ]:
np_arr = np.array([i for i in range(10000)])

start_time = process_time()
np_arr+=5

end_time = process_time()
print(end_time-start_time)

0.00035452300000038406


In [ ]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)

b = np.array([(1,2,3,4),(1,1,1,1),(3,3,3,3)])
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [1 1 1 1]
 [3 3 3 3]]
(3, 4)


In [ ]:
a = np.array([1,2,3,4], dtype=str)
print(a)

['1' '2' '3' '4']


In [32]:
#Initial placeholder in numpy.. Create an array with zeroes

arr_zeroes = np.zeros((4,4))
print(arr_zeroes)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
#create an array with ones

arr_ones = np.ones((2,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [38]:
# Create an array with particular number
x = np.full((2,2),8)
print('specific number ')
print(x)

#Create an identity matrix -- Give only the size, if 4 -> 4 row and 4 col (0 and 1)
im = np.eye(4)
print('Identity mat ')
print(im)


specific number 
[[8 8]
 [8 8]]
Identity mat 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
#Create numpy array with random value
rand = np.random.random((2,2))
print(rand)

[[0.14985029 0.02104689]
 [0.20722533 0.82483552]]


In [42]:
#Random integer within a specific range
rand = np.random.randint(10,100,(3,3))
print(rand)

[[82 80 14]
 [85 57 31]
 [71 43 21]]


In [49]:
#array of evenly spaced values --> specifying number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [51]:
#array of evenly spaced values --> specifying the range -  if 5 is given, it will add by 5

d=np.arange(10,30,6)
print(d)

[10 16 22 28]


In [52]:
li = [1,2,3,4]
convert = np.asarray(li)
print(type(convert))

<class 'numpy.ndarray'>


In [60]:
#analyse the array
arr = np.random.randint(1,10,(5,5))
# print(arr)

#Get size
print(arr.size)

#Get Shape
print(arr.shape)

#Get DataType
print(arr.dtype)

#Get dimension 2D or 1D arr
print(arr.ndim)

25
(5, 5)
int64
2


In [62]:
#Math operation

# First with list array

list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1+list2) #It will concatenate


#Now with numpy array
a = np.random.randint(1,5,(2,2))
b = np.random.randint(6,10,(2,2))

#It will do math operation based on cells in list1 and list2
print("Math operations")
print(a+b)  # or print(np.add(a,b))
print(a-b)  # or print(np.subtract(a,b))
print(a*b)  # or print(np.multiply(a,b))
print(a/b)  # or print(np.divide(a,b))
print(a%b)

[1, 2, 3, 4, 5, 6, 7, 8]
Math operations
[[ 9 13]
 [10  8]]
[[-5 -5]
 [-2 -6]]
[[14 36]
 [24  7]]
[[0.28571429 0.44444444]
 [0.66666667 0.14285714]]
[[2 4]
 [4 1]]


In [68]:
#Array Manipulation - Transpose

a = np.array([(1,2,3),(4,5,6)])

print(a.shape)
trans = np.transpose(a)  # or trans = a.T (another way for transpose <arrayname>.T)
print( trans.shape)


(2, 3)
(3, 2)


In [72]:
#Reshaping array
a = np.random.randint(1,5,(2,5))
print(a.shape)

res = a.reshape(5,2)
print(res.shape)

(2, 5)
(5, 2)
