<a href="https://colab.research.google.com/github/SoorajSundar1505/MachineLearning/blob/master/ML_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
print(9+67*2)

143


Print function


In [ ]:
from time import process_time


In [30]:
python_list = [i for i in range(10000)]
# for i in range(10000):
#   python_list.append(i)
# print(python_list)

start_time = process_time()
python_update_list = [i+5 for i in python_list]
end_time = process_time()
# print(python_update_list)
print(end_time-start_time)

0.001202091999999766


In [ ]:
import numpy as np



In [ ]:
np_arr = np.array([i for i in range(10000)])

start_time = process_time()
np_arr+=5

end_time = process_time()
print(end_time-start_time)

0.00035452300000038406


In [ ]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)

b = np.array([(1,2,3,4),(1,1,1,1),(3,3,3,3)])
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [1 1 1 1]
 [3 3 3 3]]
(3, 4)


In [ ]:
a = np.array([1,2,3,4], dtype=str)
print(a)

['1' '2' '3' '4']
