<a href="https://colab.research.google.com/github/SoorajSundar1505/MachineLearning/blob/master/Vector_Operation_in_Python_Part01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
sb.set()

In [ ]:
#Plotting a vector
plt.quiver(0,0,4,5)
plt.show()

In [ ]:
#Set proper coordinates
plt.quiver(0,0,4,5, scale_units='xy',angles='xy', scale=1, color='b')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [ ]:
#multiple vector
plt.quiver(0,0,4,5, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,-3,-8, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [22]:
#Addition of the vector
vector_1 = np.asarray([0,0,2,3])
vector_2 = np.asarray([0,0,3,-2])
sum = vector_1+vector_2
print(sum)

[0 0 5 1]


In [ ]:
#Plotting all the vectors addition
plt.quiver(0,0,2,3, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,3,-2, scale_units='xy',angles='xy', scale=1, color='r')
plt.quiver(0,0,5,1, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [23]:
#Subtraction of the vector
vector_1 = np.asarray([0,0,2,3])
vector_2 = np.asarray([0,0,3,-2])
sub = vector_1-vector_2
print(sub)

[ 0  0 -1  5]


In [ ]:
#Plotting all the vectors subtraction
plt.quiver(0,0,2,3, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,3,-2, scale_units='xy',angles='xy', scale=1, color='r')
plt.quiver(0,0,-1,5, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [25]:
#Multiple a vector by scalar
#scalers are individial num, vectors are arrays
scalar = 2
vector = np.asarray([0,0,2,3])
mul = scalar*vector;
print(mul)

[0 0 4 6]
