<a href="https://colab.research.google.com/github/SoorajSundar1505/MachineLearning/blob/master/Vector_Operation_in_Python_Part01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
sb.set()

In [ ]:
#Plotting a vector
plt.quiver(0,0,4,5)
plt.show()

In [ ]:
#Set proper coordinates
plt.quiver(0,0,4,5, scale_units='xy',angles='xy', scale=1, color='b')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [ ]:
#multiple vector
plt.quiver(0,0,4,5, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,-3,-8, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [7]:
#Addition of the vector
vector_1 = np.asarray([0,0,2,3])
vector_2 = np.asarray([0,0,3,-2])
sum = vector_1+vector_2
print(sum)

[0 0 5 1]


In [ ]:
#Plotting all the vectors addition
plt.quiver(0,0,2,3, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,3,-2, scale_units='xy',angles='xy', scale=1, color='r')
plt.quiver(0,0,5,1, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [9]:
#Subtraction of the vector
vector_1 = np.asarray([0,0,2,3])
vector_2 = np.asarray([0,0,3,-2])
sub = vector_1-vector_2
print(sub)

[ 0  0 -1  5]


In [ ]:
#Plotting all the vectors subtraction
plt.quiver(0,0,2,3, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,3,-2, scale_units='xy',angles='xy', scale=1, color='r')
plt.quiver(0,0,-1,5, scale_units='xy',angles='xy', scale=1, color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [11]:
#Multiple a vector by scalar
#scalers are individial num, vectors are arrays
scalar = 2
vector = np.asarray([0,0,2,3])
mul = scalar*vector;
print(mul)

[0 0 4 6]


In [ ]:
#Plot the multiply
plt.quiver(0,0,2,3, scale_units='xy',angles='xy', scale=1, color='b')
plt.quiver(0,0,4,6, scale_units='xy',angles='xy', scale=1, color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

In [ ]:
#Dot product - Result will be in scalar

a = np.array([2,3])
b = np.array([4,6])

dotProduct = np.dot(a,b)
print(dotProduct)


In [17]:
#Cross product of two arrays
a = np.array([2,3,7])
b = np.array([4,4,8])

a_cross_b = np.cross(a,b)
print(a_cross_b)

[-4 12 -4]


In [24]:
#Projection of two vectors
# Projection of Vector a on Vector b=a.b|m**m| * b

a = np.array([2,5,9])
b = np.array([8,-6,10])

# magnitude_of_b = np.sqrt(sum(b**2))
magnitude_of_b = np.sqrt(np.sum(b**2))
projection = (np.dot(a,b)/magnitude_of_b**2) * b
print(projection)


[ 3.04 -2.28  3.8 ]


In [ ]:
#Matrix in python

a = np.array([[1,2,3],[3,4,5]])
print(a)

#random matrix
b = np.random.rand(2,3)
print(b)

c = np.random.randint(100, size=(3,3))
print(c)

#Identity matrix
d = np.eye(3,3, dtype=int)
print(d)

#0s and 1s
e = np.ones((2,2))
print(e)

f = np.zeros((2,2))
print(f)

#Transpose
matrix = np.array([[1,2,3],[4,5,6]])
transpose = np.transpose(matrix)
print(matrix)
print(transpose)